In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv('diabetic_data.csv')

In [4]:
df

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101761,443847548,100162476,AfricanAmerican,Male,[70-80),?,1,3,7,3,...,No,Down,No,No,No,No,No,Ch,Yes,>30
101762,443847782,74694222,AfricanAmerican,Female,[80-90),?,1,4,5,5,...,No,Steady,No,No,No,No,No,No,Yes,NO
101763,443854148,41088789,Caucasian,Male,[70-80),?,1,1,7,1,...,No,Down,No,No,No,No,No,Ch,Yes,NO
101764,443857166,31693671,Caucasian,Female,[80-90),?,2,3,7,10,...,No,Up,No,No,No,No,No,Ch,Yes,NO
101765,443867222,175429310,Caucasian,Male,[70-80),?,1,1,7,6,...,No,No,No,No,No,No,No,No,No,NO

In [5]:
df.head(50)

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
5,35754,82637451,Caucasian,Male,[50-60),?,2,1,2,3,...,No,Steady,No,No,No,No,No,No,Yes,>30
6,55842,84259809,Caucasian,Male,[60-70),?,3,1,2,4,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
7,63768,114882984,Caucasian,Male,[70-80),?,1,1,7,5,...,No,No,No,No,No,No,No,No,Yes,>30
8,12522,48330783,Caucasian,Female,[80-90),?,2,1,4,13,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
9,15738,63555939,Caucasian,Female,[90-100),?,3,3,4,12,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
10,28236,89869032,AfricanAmerican,Female,[40-50),?,1,1,7,9,...,No,Steady,No,No,No,No,No,No,Yes,>30
11,36900,77391171,AfricanAmerican,Male,[60-70),?,2,1,4,7,...,No,Steady,No,No,No,No,No,Ch,Yes,<30
12,40926,85504905,Caucasian,Female,[40-50),?,1,3,7,7,...,No,Down,No,No,No,No,No,Ch,Yes,<30
13,42570,77586282,Caucasian,Male,[80-90),?,1,6,7,10,...,No,Steady,No,No,No,No,No,No,Yes,NO
14,62256,49726791,AfricanAmerican,Female,[60-70),?,3,1,2,1,...,No,Steady,No,No,No,No,No,No,Yes,>30
15,73578,86328819,AfricanAmerican,Male,[60-70),?,1,3,7,12,...,No,Up,No,No,No,No,No,Ch,Yes,NO
16,77076,92519352,AfricanAmerican,Male,[50-60),?,1,1,7,4,...,No,Steady,No,No,No,No,No,Ch,Yes,<30
17,84222,108662661,Caucasian,Female,[50-60),?,1,1,7,3,...,No,No,No,No,No,No,No,No,Yes,NO
18,89682,107389323,AfricanAmerican,Male,[70-80),?,1,1,7,5,...,No,Steady,No,No,No,No,No,No,Yes,>30
19,148530,69422211,?,Male,[70-80),?,3,6,2,6,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
20,150006,22864131,?,Female,[50-60),?,2,1,4,2,...,No,Down,No,No,No,No,No,Ch,Yes,NO
21,150048,21239181,?,Male,[60-70),?,2,1,4,2,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
22,182796,63000108,AfricanAmerican,Female,[70-80),?,2,1,4,2,...,No,No,No,No,No,No,No,No,No,NO
23,183930,107400762,Caucasian,Female,[80-90),?,2,6,1,11,...,No,No,No,No,No,No,No,No,No,>30
24,216156,62718876,AfricanAmerican,Female,[70-80),?,3,1,2,3,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
25,221634,21861756,Other,Female,[50-60),?,1,1,7,1,...,No,No,No,No,No,No,No,No,Yes,NO
26,236316,40523301,Caucasian,Male,[80-90),?,1,3,7,6,...,No,No,No,No,No,No,No,Ch,Yes,NO
27,248916,115196778,Caucasian,Female,[50-60),?,1,1,1,2,...,No,Steady,No,No,No,No,No,No,Yes,>30
28,250872,41606064,Caucasian,Male,[20-30),?,2,1,2,10,...,No,Down,No,No,No,No,No,Ch,Yes,>30
29,252822,18196434,Caucasian,Female,[80-90),?,1,2,7,5,...,No,No,No,No,No,No,No,Ch,Yes,>30
30,253380,56480238,AfricanAmerican,Female,[60-70),?,1,1,7,6,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
31,253722,96664626,AfricanAmerican,Male,[70-80),?,1,5,7,1,...,No,Down,No,No,No,No,No,Ch,Yes,>30
32,260166,80845353,Caucasian,Female,[70-80),?,1,1,7,6,...,No,Steady,No,No,No,No,No,No,Yes,>30
33,293058,114715242,Caucasian,Male,[60-70),?,2,6,2,5,...,No,Steady,No,No,No,No,No,No,Yes,>30
34,293118,3327282,Caucasian,Female,[70-80),?,2,11,2,5,...,No,Down,No,No,No,No,No,Ch,Yes,NO
35,325848,63023292,Caucasian,Female,[60-70),?,1,1,7,2,...,No,Down,No,No,No,No,No,Ch,Yes,>30
36,325866,98427861,Caucasian,Female,[70-80),?,3,1,2,3,...,No,Steady,No,No,No,No,No,No,Yes,NO
37,326028,112002975,Caucasian,Female,[60-70),?,1,1,7,4,...,No,Steady,No,No,No,No,No,Ch,Yes,>30
38,358776,101002446,Caucasian,Male,[70-80),?,1,6,7,7,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
39,377268,104672268,Caucasian,Male,[50-60),?,2,1,2,1,...,No,Steady,No,No,No,No,No,No,Yes,>30
40,383430,80588529,Caucasian,Female,[70-80),?,1,2,7,1,...,No,Down,No,No,No,No,No,Ch,Yes,>30
41,419304,99715041,Caucasian,Male,[40-50),?,2,1,2,7,...,No,Steady,No,No,No,No,No,No,Yes,>30
42,421194,96435585,Caucasian,Female,[70-80),?,2,1,1,13,...,No,Steady,No,No,No,No,No,Ch,Yes,>30
43,449142,66274866,Caucasian,Male,[50-60),?,1,1,7,3,...,No,Steady,No,No,No,No,No,Ch,Yes,>30
44,450210,80177094,Caucasian,Female,[80-90),?,1,11,7,7,...,No,Steady,No,No,No,No,No,No,Yes,NO
45,464994,106936875,Caucasian,Female,[40-50),?,3,1,2,2,...,No,Steady,No,No,No,No,No,No,Yes,NO
46,486156,86240259,Caucasian,Female,[70-80),?,3,5,4,9,...,No,Down,No,No,No,No,No,Ch,Yes,<30
47,498030,51838164,Caucasian,Male,[70-80),?,3,3,4,9,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
48,537834,90097839,Caucasian,Male,[50-60),?,3,1,2,6,...,No,Up,No,No,No,No,No,Ch,Yes,NO
49,544194,34997814,Caucasian,Male,[60-70),?,2,6,4,11,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [6]:
df.tail()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
101761,443847548,100162476,AfricanAmerican,Male,[70-80),?,1,3,7,3,...,No,Down,No,No,No,No,No,Ch,Yes,>30
101762,443847782,74694222,AfricanAmerican,Female,[80-90),?,1,4,5,5,...,No,Steady,No,No,No,No,No,No,Yes,NO
101763,443854148,41088789,Caucasian,Male,[70-80),?,1,1,7,1,...,No,Down,No,No,No,No,No,Ch,Yes,NO
101764,443857166,31693671,Caucasian,Female,[80-90),?,2,3,7,10,...,No,Up,No,No,No,No,No,Ch,Yes,NO
101765,443867222,175429310,Caucasian,Male,[70-80),?,1,1,7,6,...,No,No,No,No,No,No,No,No,No,NO

In [7]:
df.shape

(101766, 50)

In [8]:
df.info

<bound method DataFrame.info of         encounter_id  patient_nbr             race  gender      age weight  \
0            2278392      8222157        Caucasian  Female   [0-10)      ?
1             149190     55629189        Caucasian  Female  [10-20)      ?
2              64410     86047875  AfricanAmerican  Female  [20-30)      ?
3             500364     82442376        Caucasian    Male  [30-40)      ?
4              16680     42519267        Caucasian    Male  [40-50)      ?
...              ...          ...              ...     ...      ...    ...
101761     443847548    100162476  AfricanAmerican    Male  [70-80)      ?
101762     443847782     74694222  AfricanAmerican  Female  [80-90)      ?
101763     443854148     41088789        Caucasian    Male  [70-80)      ?
101764     443857166     31693671        Caucasian  Female  [80-90)      ?
101765     443867222    175429310        Caucasian    Male  [70-80)      ?

        admission_type_id  discharge_disposition_id  admission_source_id  \
0                       6                        25                    1
1                       1                         1                    7
2                       1                         1                    7
3                       1                         1                    7
4                       1                         1                    7
...                   ...                       ...                  ...
101761                  1                         3                    7
101762                  1                         4                    5
101763                  1                         1                    7
101764                  2                         3                    7
101765                  1                         1                    7

        time_in_hospital  ... citoglipton insulin  glyburide-metformin  \
0                      1  ...          No      No                   No
1                      3  ...          No      Up                   No
2                      2  ...          No      No                   No
3                      2  ...          No      Up                   No
4                      1  ...          No  Steady                   No
...                  ...  ...         ...     ...                  ...
101761                 3  ...          No    Down                   No
101762                 5  ...          No  Steady                   No
101763                 1  ...          No    Down                   No
101764                10  ...          No      Up                   No
101765                 6  ...          No      No                   No

        glipizide-metformin  glimepiride-pioglitazone  \
0                        No                        No
1                        No                        No
2                        No                        No
3                        No                        No
4                        No                        No
...                     ...                       ...
101761                   No                        No
101762                   No                        No
101763                   No                        No
101764                   No                        No
101765                   No                        No

        metformin-rosiglitazone  metformin-pioglitazone  change diabetesMed  \
0                            No                      No      No          No
1                            No                      No      Ch         Yes
2                            No                      No      No         Yes
3                            No                      No      Ch         Yes
4                            No                      No      Ch         Yes
...                         ...                     ...     ...         ...
101761                       No                      No      Ch         Yes
101762                       No                      No      No         Yes
101763                       No                      No      Ch         Yes
101764                       No                      No      Ch         Yes
101765                       No                      No      No          No

       readmitted
0              NO
1             >30
2              NO
3              NO
4              NO
...           ...
101761        >30
101762         NO
101763         NO
101764         NO
101765         NO

[101766 rows x 50 columns]>

In [9]:
df.describe()

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,1.017660e+05,1.017660e+05,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000
mean,1.652016e+08,5.433040e+07,2.024006,3.715642,5.754437,4.395987,43.095641,1.339730,16.021844,0.369357,0.197836,0.635566,7.422607
std,1.026403e+08,3.869636e+07,1.445403,5.280166,4.064081,2.985108,19.674362,1.705807,8.127566,1.267265,0.930472,1.262863,1.933600
min,1.252200e+04,1.350000e+02,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,8.496119e+07,2.341322e+07,1.000000,1.000000,1.000000,2.000000,31.000000,0.000000,10.000000,0.000000,0.000000,0.000000,6.000000
50%,1.523890e+08,4.550514e+07,1.000000,1.000000,7.000000,4.000000,44.000000,1.000000,15.000000,0.000000,0.000000,0.000000,8.000000
75%,2.302709e+08,8.754595e+07,3.000000,4.000000,7.000000,6.000000,57.000000,2.000000,20.000000,0.000000,0.000000,1.000000,9.000000
max,4.438672e+08,1.895026e+08,8.000000,28.000000,25.000000,14.000000,132.000000,6.000000,81.000000,42.000000,76.000000,21.000000,16.000000

In [10]:
df.dropna(axis=0)

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
162,2521974,80499960,Caucasian,Male,[80-90),?,6,3,7,5,...,No,No,No,No,No,No,No,No,No,<30
192,2595612,89193870,Caucasian,Female,[40-50),?,6,1,7,2,...,No,No,No,No,No,No,No,No,No,>30
460,4084524,76959585,AfricanAmerican,Female,[70-80),?,6,1,7,10,...,No,Up,No,No,No,No,No,Ch,Yes,>30
593,4804968,114960726,Caucasian,Female,[50-60),?,6,1,7,2,...,No,Steady,No,No,No,No,No,No,Yes,NO
696,5319174,87847776,Other,Male,[70-80),?,6,6,7,11,...,No,No,No,No,No,No,No,No,Yes,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100386,424989572,103832127,Caucasian,Male,[60-70),?,2,1,1,6,...,No,No,No,No,No,No,No,No,Yes,<30
100493,426670736,101755908,Caucasian,Female,[40-50),?,1,1,7,3,...,No,No,No,No,No,No,No,No,No,NO
100578,427875206,90285327,Caucasian,Female,[60-70),?,1,2,7,4,...,No,No,No,No,No,No,No,No,No,NO
101029,433822712,104106645,Caucasian,Male,[50-60),?,1,1,7,7,...,No,No,No,No,No,No,No,Ch,Yes,>30
101088,434900486,126428594,AfricanAmerican,Male,[40-50),?,6,7,7,2,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [11]:
df

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101761,443847548,100162476,AfricanAmerican,Male,[70-80),?,1,3,7,3,...,No,Down,No,No,No,No,No,Ch,Yes,>30
101762,443847782,74694222,AfricanAmerican,Female,[80-90),?,1,4,5,5,...,No,Steady,No,No,No,No,No,No,Yes,NO
101763,443854148,41088789,Caucasian,Male,[70-80),?,1,1,7,1,...,No,Down,No,No,No,No,No,Ch,Yes,NO
101764,443857166,31693671,Caucasian,Female,[80-90),?,2,3,7,10,...,No,Up,No,No,No,No,No,Ch,Yes,NO
101765,443867222,175429310,Caucasian,Male,[70-80),?,1,1,7,6,...,No,No,No,No,No,No,No,No,No,NO

In [12]:
df.dropna(axis=1)

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101761,443847548,100162476,AfricanAmerican,Male,[70-80),?,1,3,7,3,...,No,Down,No,No,No,No,No,Ch,Yes,>30
101762,443847782,74694222,AfricanAmerican,Female,[80-90),?,1,4,5,5,...,No,Steady,No,No,No,No,No,No,Yes,NO
101763,443854148,41088789,Caucasian,Male,[70-80),?,1,1,7,1,...,No,Down,No,No,No,No,No,Ch,Yes,NO
101764,443857166,31693671,Caucasian,Female,[80-90),?,2,3,7,10,...,No,Up,No,No,No,No,No,Ch,Yes,NO
101765,443867222,175429310,Caucasian,Male,[70-80),?,1,1,7,6,...,No,No,No,No,No,No,No,No,No,NO

In [13]:
df.replace([ '?' , 'nil' , 'na' , ' '] , np.nan , inplace =True)

In [14]:
df.dropna(axis=0)

Empty DataFrame
Columns: [encounter_id, patient_nbr, race, gender, age, weight, admission_type_id, discharge_disposition_id, admission_source_id, time_in_hospital, payer_code, medical_specialty, num_lab_procedures, num_procedures, num_medications, number_outpatient, number_emergency, number_inpatient, diag_1, diag_2, diag_3, number_diagnoses, max_glu_serum, A1Cresult, metformin, repaglinide, nateglinide, chlorpropamide, glimepiride, acetohexamide, glipizide, glyburide, tolbutamide, pioglitazone, rosiglitazone, acarbose, miglitol, troglitazone, tolazamide, examide, citoglipton, insulin, glyburide-metformin, glipizide-metformin, glimepiride-pioglitazone, metformin-rosiglitazone, metformin-pioglitazone, change, diabetesMed, readmitted]
Index: []

[0 rows x 50 columns]

In [15]:
df.dropna(axis=1)

,encounter_id,patient_nbr,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Female,[0-10),6,25,1,1,41,0,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Female,[10-20),1,1,7,3,59,0,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,Female,[20-30),1,1,7,2,11,5,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Male,[30-40),1,1,7,2,44,1,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Male,[40-50),1,1,7,1,51,0,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101761,443847548,100162476,Male,[70-80),1,3,7,3,51,0,...,No,Down,No,No,No,No,No,Ch,Yes,>30
101762,443847782,74694222,Female,[80-90),1,4,5,5,33,3,...,No,Steady,No,No,No,No,No,No,Yes,NO
101763,443854148,41088789,Male,[70-80),1,1,7,1,53,0,...,No,Down,No,No,No,No,No,Ch,Yes,NO
101764,443857166,31693671,Female,[80-90),2,3,7,10,45,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
101765,443867222,175429310,Male,[70-80),1,1,7,6,13,3,...,No,No,No,No,No,No,No,No,No,NO

In [16]:
df.columns

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted'],
      dtype='object')

In [17]:
df.isna().sum()

encounter_id                    0
patient_nbr                     0
race                         2273
gender                          0
age                             0
weight                      98569
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                  40256
medical_specialty           49949
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                         21
diag_2                        358
diag_3                       1423
number_diagnoses                0
max_glu_serum               96420
A1Cresult                   84748
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [18]:
df_cleaned = df.dropna(axis=1)

In [19]:
df_cleaned

,encounter_id,patient_nbr,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Female,[0-10),6,25,1,1,41,0,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Female,[10-20),1,1,7,3,59,0,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,Female,[20-30),1,1,7,2,11,5,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Male,[30-40),1,1,7,2,44,1,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Male,[40-50),1,1,7,1,51,0,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101761,443847548,100162476,Male,[70-80),1,3,7,3,51,0,...,No,Down,No,No,No,No,No,Ch,Yes,>30
101762,443847782,74694222,Female,[80-90),1,4,5,5,33,3,...,No,Steady,No,No,No,No,No,No,Yes,NO
101763,443854148,41088789,Male,[70-80),1,1,7,1,53,0,...,No,Down,No,No,No,No,No,Ch,Yes,NO
101764,443857166,31693671,Female,[80-90),2,3,7,10,45,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
101765,443867222,175429310,Male,[70-80),1,1,7,6,13,3,...,No,No,No,No,No,No,No,No,No,NO

In [20]:
df_cleaned.columns

Index(['encounter_id', 'patient_nbr', 'gender', 'age', 'admission_type_id',
       'discharge_disposition_id', 'admission_source_id', 'time_in_hospital',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient',
       'number_diagnoses', 'metformin', 'repaglinide', 'nateglinide',
       'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide',
       'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose',
       'miglitol', 'troglitazone', 'tolazamide', 'examide', 'citoglipton',
       'insulin', 'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted'],
      dtype='object')

In [21]:
df_cleaned.drop('encounter_id')

KeyError: "['encounter_id'] not found in axis"

In [ ]:
df_cleaned.to_csv('Cleaned_data.csv' , index=False)

In [ ]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 41 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   gender                    101766 non-null  object
 3   age                       101766 non-null  object
 4   admission_type_id         101766 non-null  int64
 5   discharge_disposition_id  101766 non-null  int64
 6   admission_source_id       101766 non-null  int64
 7   time_in_hospital          101766 non-null  int64
 8   num_lab_procedures        101766 non-null  int64
 9   num_procedures            101766 non-null  int64
 10  num_medications           101766 non-null  int64
 11  number_outpatient         101766 non-null  int64
 12  number_emergency          101766 non-null  int64
 13  number_inpatient          101766 non-null  int64
 14  number_diagnoses          101766 non-null  int64
 15  metformin                 101766 non-null  object
 16  repaglinide               101766 non-null  object
 17  nateglinide               101766 non-null  object
 18  chlorpropamide            101766 non-null  object
 19  glimepiride               101766 non-null  object
 20  acetohexamide             101766 non-null  object
 21  glipizide                 101766 non-null  object
 22  glyburide                 101766 non-null  object
 23  tolbutamide               101766 non-null  object
 24  pioglitazone              101766 non-null  object
 25  rosiglitazone             101766 non-null  object
 26  acarbose                  101766 non-null  object
 27  miglitol                  101766 non-null  object
 28  troglitazone              101766 non-null  object
 29  tolazamide                101766 non-null  object
 30  examide                   101766 non-null  object
 31  citoglipton               101766 non-null  object
 32  insulin                   101766 non-null  object
 33  glyburide-metformin       101766 non-null  object
 34  glipizide-metformin       101766 non-null  object
 35  glimepiride-pioglitazone  101766 non-null  object
 36  metformin-rosiglitazone   101766 non-null  object
 37  metformin-pioglitazone    101766 non-null  object
 38  change                    101766 non-null  object
 39  diabetesMed               101766 non-null  object
 40  readmitted                101766 non-null  object
dtypes: int64(13), object(28)
memory usage: 31.8+ MB

In [ ]:
df_cleaned.gender.unique()

array(['Female', 'Male', 'Unknown/Invalid'], dtype=object)

In [ ]:
df_cleaned.age.unique()

array(['[0-10)', '[10-20)', '[20-30)', '[30-40)', '[40-50)', '[50-60)',
       '[60-70)', '[70-80)', '[80-90)', '[90-100)'], dtype=object)

In [22]:
df2 = pd.read_csv('diabetic_data.csv')
print(df2.head())

   encounter_id  patient_nbr             race  gender      age weight  \
0       2278392      8222157        Caucasian  Female   [0-10)      ?
1        149190     55629189        Caucasian  Female  [10-20)      ?
2         64410     86047875  AfricanAmerican  Female  [20-30)      ?
3        500364     82442376        Caucasian    Male  [30-40)      ?
4         16680     42519267        Caucasian    Male  [40-50)      ?

   admission_type_id  discharge_disposition_id  admission_source_id  \
0                  6                        25                    1
1                  1                         1                    7
2                  1                         1                    7
3                  1                         1                    7
4                  1                         1                    7

   time_in_hospital  ... citoglipton insulin  glyburide-metformin  \
0                 1  ...          No      No                   No
1                 3  ...          No      Up                   No
2                 2  ...          No      No                   No
3                 2  ...          No      Up                   No
4                 1  ...          No  Steady                   No

   glipizide-metformin  glimepiride-pioglitazone  metformin-rosiglitazone  \
0                   No                        No                       No
1                   No                        No                       No
2                   No                        No                       No
3                   No                        No                       No
4                   No                        No                       No

   metformin-pioglitazone  change diabetesMed readmitted
0                      No      No          No         NO
1                      No      Ch         Yes        >30
2                      No      No         Yes         NO
3                      No      Ch         Yes         NO
4                      No      Ch         Yes         NO

[5 rows x 50 columns]

In [23]:
from sklearn.impute import SimpleImputer

In [25]:
nums_only = df2.select_dtypes(include='number')

In [26]:
imputer = SimpleImputer(strategy='mean')
imputer.fit_transform(nums_only)

array([[2.27839200e+06, 8.22215700e+06, 6.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [1.49190000e+05, 5.56291890e+07, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 9.00000000e+00],
       [6.44100000e+04, 8.60478750e+07, 1.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 6.00000000e+00],
       ...,
       [4.43854148e+08, 4.10887890e+07, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.30000000e+01],
       [4.43857166e+08, 3.16936710e+07, 2.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 9.00000000e+00],
       [4.43867222e+08, 1.75429310e+08, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 9.00000000e+00]],
      shape=(101766, 13))