In [90]:
import pandas as pd

In [91]:
mydata = [1776, 1867 , 1821]
myseries = pd.Series(data = mydata)
print(myseries)

0    1776
1    1867
2    1821
dtype: int64

In [92]:
data1 = [1254, 1833 , 1433, 1773]
myseries2 = pd.Series(data = data1)
myseries2

0    1254
1    1833
2    1433
3    1773
dtype: int64

In [93]:
myseries+myseries2

0    3030.0
1    3700.0
2    3254.0
3       NaN
dtype: float64

In [94]:
my_index = ['USA' , 'Canada' , 'Mexico', 'India']
mydata1 = [1455, 678 , 987 ,455]
myseries1 = pd.Series(data = mydata1 , index = my_index , name = 'Numbers')
myseries1

USA       1455
Canada     678
Mexico     987
India      455
Name: Numbers, dtype: int64

In [95]:
myseries1.keys()

Index(['USA', 'Canada', 'Mexico', 'India'], dtype='object')

In [96]:
type(myseries1)

pandas.core.series.Series

In [97]:
myseries[0]

np.int64(1776)

In [98]:
myseries1['USA']

np.int64(1455)

In [99]:
myseries1[0]

C:\Users\Ariba\AppData\Local\Temp\ipykernel_15240\92473884.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  myseries1[0]

np.int64(1455)

In [100]:
myseries.add(myseries1, fill_value= 0)

0         1776.0
1         1867.0
2         1821.0
Canada     678.0
India      455.0
Mexico     987.0
USA       1455.0
dtype: float64

In [101]:
r = [1 ,2]
ser = pd.Series(r , copy = False)
ser.iloc[0] = 99
ser

0    99
1     2
dtype: int64

In [102]:
myseries.add(123 , fill_value = 0)

0    1899
1    1990
2    1944
dtype: int64

In [103]:
import numpy as np

In [104]:
from numpy.random import randn

In [105]:
np.random.seed(105)

In [106]:
df = pd.DataFrame(randn(5,4) , index = 'A B C D E'.split() , columns = 'W X Y Z'.split())

In [107]:
df

          W         X         Y         Z
A -0.245326 -0.613352 -0.726768  0.059366
B  1.005580 -0.128140 -1.533992  0.470710
C -0.555311 -0.204716  1.704763  2.573846
D  0.555636  0.950649 -1.405614  1.420322
E -1.286894  0.142174  0.689817 -0.302278

In [108]:
df['W']

A   -0.245326
B    1.005580
C   -0.555311
D    0.555636
E   -1.286894
Name: W, dtype: float64

In [109]:
df[['W' , 'X']]

          W         X
A -0.245326 -0.613352
B  1.005580 -0.128140
C -0.555311 -0.204716
D  0.555636  0.950649
E -1.286894  0.142174

In [110]:
type(df)

pandas.core.frame.DataFrame

In [111]:
type(df['W'])

pandas.core.series.Series

In [112]:
df['G'] = df['X'] + df['Z']

In [113]:
df

          W         X         Y         Z         G
A -0.245326 -0.613352 -0.726768  0.059366 -0.553986
B  1.005580 -0.128140 -1.533992  0.470710  0.342570
C -0.555311 -0.204716  1.704763  2.573846  2.369129
D  0.555636  0.950649 -1.405614  1.420322  2.370971
E -1.286894  0.142174  0.689817 -0.302278 -0.160104

In [114]:
from numpy.random import randint

In [115]:
df1 = pd.DataFrame(randint(50, 100,20).reshape(5,4) , index = 'A B C D E'.split() , columns = 'W X Y Z'.split())

In [116]:
df1

    W   X   Y   Z
A  59  52  71  56
B  50  68  96  60
C  74  80  75  69
D  99  93  67  74
E  67  98  52  50

In [117]:
df1.drop('X', axis = 1, inplace = True)

In [118]:
df1

    W   Y   Z
A  59  71  56
B  50  96  60
C  74  75  69
D  99  67  74
E  67  52  50

In [119]:
df.drop('A', axis = 0)

          W         X         Y         Z         G
B  1.005580 -0.128140 -1.533992  0.470710  0.342570
C -0.555311 -0.204716  1.704763  2.573846  2.369129
D  0.555636  0.950649 -1.405614  1.420322  2.370971
E -1.286894  0.142174  0.689817 -0.302278 -0.160104

In [120]:
df

          W         X         Y         Z         G
A -0.245326 -0.613352 -0.726768  0.059366 -0.553986
B  1.005580 -0.128140 -1.533992  0.470710  0.342570
C -0.555311 -0.204716  1.704763  2.573846  2.369129
D  0.555636  0.950649 -1.405614  1.420322  2.370971
E -1.286894  0.142174  0.689817 -0.302278 -0.160104

In [121]:
df.loc[:,'W']

A   -0.245326
B    1.005580
C   -0.555311
D    0.555636
E   -1.286894
Name: W, dtype: float64

In [122]:
df.loc['A']

W   -0.245326
X   -0.613352
Y   -0.726768
Z    0.059366
G   -0.553986
Name: A, dtype: float64

In [123]:
df.iloc[3]

W    0.555636
X    0.950649
Y   -1.405614
Z    1.420322
G    2.370971
Name: D, dtype: float64

In [124]:
df.loc[['A', 'B'] ,['W' , 'Z']]

          W         Z
A -0.245326  0.059366
B  1.005580  0.470710

In [125]:
df[df>0]

          W         X         Y         Z         G
A       NaN       NaN       NaN  0.059366       NaN
B  1.005580       NaN       NaN  0.470710  0.342570
C       NaN       NaN  1.704763  2.573846  2.369129
D  0.555636  0.950649       NaN  1.420322  2.370971
E       NaN  0.142174  0.689817       NaN       NaN

In [126]:
df[df['W']>0]

          W         X         Y         Z         G
B  1.005580 -0.128140 -1.533992  0.470710  0.342570
D  0.555636  0.950649 -1.405614  1.420322  2.370971

In [127]:
data_inf = { 'Name' : ['Ariba' , 'Aliza' , 'Zara', 'Aqdas', 'Aanya'] , 'Age' : [14 , np.nan,18, 16, np.nan] , 'Weight' : [55, 45 , 65 , 40, np.nan]}
mydf = pd.DataFrame(data_inf)
print(mydf)

    Name   Age  Weight
0  Ariba  14.0    55.0
1  Aliza   NaN    45.0
2   Zara  18.0    65.0
3  Aqdas  16.0    40.0
4  Aanya   NaN     NaN

In [128]:
mydf.dropna(axis=0)

    Name   Age  Weight
0  Ariba  14.0    55.0
2   Zara  18.0    65.0
3  Aqdas  16.0    40.0

In [129]:
mydf.dropna(axis=1)

    Name
0  Ariba
1  Aliza
2   Zara
3  Aqdas
4  Aanya

In [130]:
mydf.dropna(axis=0 , thresh=3)

    Name   Age  Weight
0  Ariba  14.0    55.0
2   Zara  18.0    65.0
3  Aqdas  16.0    40.0

In [131]:
mydf.fillna(value=0)

    Name   Age  Weight
0  Ariba  14.0    55.0
1  Aliza   0.0    45.0
2   Zara  18.0    65.0
3  Aqdas  16.0    40.0
4  Aanya   0.0     0.0

In [132]:
mydf

    Name   Age  Weight
0  Ariba  14.0    55.0
1  Aliza   NaN    45.0
2   Zara  18.0    65.0
3  Aqdas  16.0    40.0
4  Aanya   NaN     NaN

In [133]:
mydf.fillna(value=mydf['Age'].mean(numeric_only=True))

    Name   Age  Weight
0  Ariba  14.0    55.0
1  Aliza  16.0    45.0
2   Zara  18.0    65.0
3  Aqdas  16.0    40.0
4  Aanya  16.0    16.0

In [134]:
mydf.fillna(value=mydf['Age'].min(numeric_only=True))

    Name   Age  Weight
0  Ariba  14.0    55.0
1  Aliza  14.0    45.0
2   Zara  18.0    65.0
3  Aqdas  16.0    40.0
4  Aanya  14.0    14.0

In [135]:
mydf

    Name   Age  Weight
0  Ariba  14.0    55.0
1  Aliza   NaN    45.0
2   Zara  18.0    65.0
3  Aqdas  16.0    40.0
4  Aanya   NaN     NaN

In [136]:
mydf['Class'] = ['MCA' ,'BCA' , 'BSC' ,'MCA' , 'MCA']
print(mydf)

    Name   Age  Weight Class
0  Ariba  14.0    55.0   MCA
1  Aliza   NaN    45.0   BCA
2   Zara  18.0    65.0   BSC
3  Aqdas  16.0    40.0   MCA
4  Aanya   NaN     NaN   MCA

In [137]:
mydf.groupby('Class')

In [138]:
newdf = mydf.groupby('Class')
newdf.mean(numeric_only=True)

        Age  Weight
Class
BCA     NaN    45.0
BSC    18.0    65.0
MCA    15.0    47.5

In [139]:
newdf.count()

       Name  Age  Weight
Class
BCA       1    0       1
BSC       1    1       1
MCA       3    2       2

In [140]:
newdf.describe()

        Age                                               Weight        \
      count  mean       std   min   25%   50%   75%   max  count  mean
Class
BCA     0.0   NaN       NaN   NaN   NaN   NaN   NaN   NaN    1.0  45.0
BSC     1.0  18.0       NaN  18.0  18.0  18.0  18.0  18.0    1.0  65.0
MCA     2.0  15.0  1.414214  14.0  14.5  15.0  15.5  16.0    2.0  47.5


             std   min    25%   50%    75%   max
Class
BCA          NaN  45.0  45.00  45.0  45.00  45.0
BSC          NaN  65.0  65.00  65.0  65.00  65.0
MCA    10.606602  40.0  43.75  47.5  51.25  55.0

In [141]:
data_inf2 = { 'USA': [12 , 14, 15] , 'Canada' : [65 , 77 , np.nan]}
mydf_2 = pd.DataFrame(data_inf2)
print(mydf_2)

   USA  Canada
0   12    65.0
1   14    77.0
2   15     NaN

In [142]:
data_inf3 = {'India' :[11 ,45 , 67] , 'Mexico' : [45 ,77 ,80]}
mydf_3 = pd.DataFrame(data_inf3)
print(mydf_3)

   India  Mexico
0     11      45
1     45      77
2     67      80

In [150]:
nf = pd.concat([mydf_3,mydf_2]).reset_index()
print(nf)

   index  India  Mexico   USA  Canada
0      0   11.0    45.0   NaN     NaN
1      1   45.0    77.0   NaN     NaN
2      2   67.0    80.0   NaN     NaN
3      0    NaN     NaN  12.0    65.0
4      1    NaN     NaN  14.0    77.0
5      2    NaN     NaN  15.0     NaN

In [144]:
mydf

    Name   Age  Weight Class
0  Ariba  14.0    55.0   MCA
1  Aliza   NaN    45.0   BCA
2   Zara  18.0    65.0   BSC
3  Aqdas  16.0    40.0   MCA
4  Aanya   NaN     NaN   MCA

In [145]:
mydf_2

   USA  Canada
0   12    65.0
1   14    77.0
2   15     NaN